# Generated by Django 5.1.4 on 2025-07-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_date',
            new_name='created_at_date',
        ),
    ]
